import 'package:athlete_go/aag_testing/logic/sh_hive_model.dart';

List<ShHiveModel> sportList = [
  ShHiveModel(
    title: 'Take a walk',
    imageUrl: 'assets/images/s1.png',
    totalDays: 5,
    times: {
      'Sun': false,
      'Mon': false,
      'Tue': false,
      'Fri': false,
      'Sat': false,
    },
  ),
  ShHiveModel(
    title: 'Regular training',
    imageUrl: 'assets/images/s2.png',
    totalDays: 7,
    times: {
      'Sun': false,
      'Mon': false,
      'Tue': false,
      'Wed': false,
      'Thu': false,
      'Fri': false,
      'Sat': false,
    },
  ),
  ShHiveModel(
    title: '10,000 steps',
    imageUrl: 'assets/images/s3.png',
    totalDays: 5,
    times: {
      'Sun': false,
      'Mon': false,
      'Tue': false,
      'Fri': false,
      'Sat': false,
    },
  ),
  ShHiveModel(
    title: 'Take a bike ride',
    imageUrl: 'assets/images/s4.png',
    totalDays: 7,
    times: {
      'Sun': false,
      'Mon': false,
      'Tue': false,
      'Wed': false,
      'Thu': false,
      'Fri': false,
      'Sat': false,
    },
  ),
  ShHiveModel(
    title: 'Visit the gym',
    imageUrl: 'assets/images/s5.png',
    totalDays: 7,
    times: {
      'Sun': false,
      'Mon': false,
      'Tue': false,
      'Wed': false,
      'Thu': false,
      'Fri': false,
      'Sat': false,
    },
  ),
  ShHiveModel(
    title: 'Swim',
    imageUrl: 'assets/images/s6.png',
    totalDays: 7,
    times: {
      'Sun': false,
      'Mon': false,
      'Tue': false,
      'Wed': false,
      'Thu': false,
      'Fri': false,
      'Sat': false,
    },
  ),
  ShHiveModel(
    title: 'Stretching before bed',
    imageUrl: 'assets/images/s7.png',
    totalDays: 7,
    times: {
      'Sun': false,
      'Mon': false,
      'Tue': false,
      'Wed': false,
      'Thu': false,
      'Fri': false,
      'Sat': false,
    },
  ),
  ShHiveModel(
    title: 'Walk through the mountains and nature',
    imageUrl: 'assets/images/s8.png',
    totalDays: 7,
    times: {
      'Sun': false,
      'Mon': false,
      'Tue': false,
      'Wed': false,
      'Thu': false,
      'Fri': false,
      'Sat': false,
    },
  ),
];

List<ShHiveModel> healthList = [
  ShHiveModel(
    title: 'Take your vitamins',
    imageUrl: 'assets/images/s1.png',
    totalDays: 5,
    times: {
      'Sun': false,
      'Mon': false,
      'Tue': false,
      'Fri': false,
      'Sat': false,
    },
  ),
  ShHiveModel(
    title: 'Day without sugar',
    imageUrl: 'assets/images/s2.png',
    totalDays: 7,
    times: {
      'Sun': false,
      'Mon': false,
      'Tue': false,
      'Wed': false,
      'Thu': false,
      'Fri': false,
      'Sat': false,
    },
  ),
  ShHiveModel(
    title: 'Go to bed early',
    imageUrl: 'assets/images/s3.png',
    totalDays: 5,
    times: {
      'Sun': false,
      'Mon': false,
      'Tue': false,
      'Fri': false,
      'Sat': false,
    },
  ),
  ShHiveModel(
    title: 'Eat more fruits and greens',
    imageUrl: 'assets/images/s4.png',
    totalDays: 7,
    times: {
      'Sun': false,
      'Mon': false,
      'Tue': false,
      'Wed': false,
      'Thu': false,
      'Fri': false,
      'Sat': false,
    },
  ),
  ShHiveModel(
    title: 'Stop smoking',
    imageUrl: 'assets/images/s5.png',
    totalDays: 7,
    times: {
      'Sun': false,
      'Mon': false,
      'Tue': false,
      'Wed': false,
      'Thu': false,
      'Fri': false,
      'Sat': false,
    },
  ),
  ShHiveModel(
    title: 'No food before bed',
    imageUrl: 'assets/images/s6.png',
    totalDays: 7,
    times: {
      'Sun': false,
      'Mon': false,
      'Tue': false,
      'Wed': false,
      'Thu': false,
      'Fri': false,
      'Sat': false,
    },
  ),
  ShHiveModel(
    title: ' Drink more water',
    imageUrl: 'assets/images/s7.png',
    totalDays: 7,
    times: {
      'Sun': false,
      'Mon': false,
      'Tue': false,
      'Wed': false,
      'Thu': false,
      'Fri': false,
      'Sat': false,
    },
  ),
  ShHiveModel(
    title: 'No electronics before bed',
    imageUrl: 'assets/images/s8.png',
    totalDays: 7,
    times: {
      'Sun': false,
      'Mon': false,
      'Tue': false,
      'Wed': false,
      'Thu': false,
      'Fri': false,
      'Sat': false,
    },
  ),
];
